# Generated by Django 2.2.3 on 2019-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
