# Generated by Django 2.2.3 on 2019-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_usercreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('conform_password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
