# Generated by Django 2.2.3 on 2019-08-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_auto_20190810_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregister',
            old_name='uname',
            new_name='username',
        ),
    ]
