# Generated by Django 2.2.3 on 2019-08-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_auto_20190810_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'AcceptedList',
            },
        ),
    ]
