# Generated by Django 2.2.3 on 2019-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_auto_20190810_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(help_text='Already this mobile number is Exists', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(help_text='Already this email is Exists', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(help_text='Already this eid is Exists', max_length=20, unique=True),
        ),
    ]
