# Generated by Django 2.2.3 on 2019-08-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_auto_20190810_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(help_text='Already this mobile number is Exists', unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(help_text='Already this eid is Exists', unique=True),
        ),
    ]
